In [0]:
import numpy as np

In [0]:
def neighbors(a, i, j):
    """returns all neighbors of element with index (i,j)
    in array assuming array is 2d.
    """
    
    result = []
    row_above = i-1 >= 0
    row_below = i+1 <= a.shape[0]-1
    col_left = j-1 >= 0
    col_right = j+1 <=  a.shape[0]-1

    if row_below:
      result.append((i+1, j))
      #if col_right:
        #result.append((i+1, j+1))
      #if col_left:
        #result.append((i+1, j-1))
    
    if col_right:
        result.append((i, j+1))
      
    if row_above:
        result.append((i-1, j))
        #if col_left:
         #   result.append((i-1, j-1))
        #if col_right:
         #   result.append((i-1,j+1))
    if col_left:
        result.append((i, j-1))
    

    return result

In [0]:
def filtering_neighbors(lst_neighbors,arr,dist_matrix,i,j):
  filtered_n=[]
  filtered_neighbors=[]
  for idx in lst_neighbors:
    if(arr[idx[0]][idx[1]]==0):
      filtered_n.append(idx)
  for idx in filtered_n:
    if(dist_matrix[i][j]+1 < dist_matrix[idx[0]][idx[1]]):
      dist_matrix[idx[0]][idx[1]]=dist_matrix[i][j]+1
      filtered_neighbors.append(idx)
  return filtered_neighbors,dist_matrix



In [0]:
def drawpath(matrix,i,j):
  nearby=neighbors(matrix,i,j)
  current_value=matrix[i][j]
  matrix[i][j]='300'
  for n in nearby:
    if((current_value-1==matrix[n[0]][n[1]])):
      drawpath(matrix,n[0],n[1])
      break
  return matrix

  

In [0]:
def chessboard(path):
  for i in range(matrix.shape[0]):
    for j in range(matrix.shape[0]):
      if(path[i][j]!=1000 and path[i][j]!=300):
        path[i][j]=0
      elif(path[i][j]==1000):
        path[i][j]=1
      elif(path[i][j]==300):
        path[i][j]=2
  return path      


In [0]:
def Shortest_path(arr,i,j,dist_matrix):
  if(i+j==(arr.shape[0]-1)*2):
    return dist_matrix
  n=neighbors(arr,i,j)
  t=filtering_neighbors(n,arr,dist_matrix,i,j)
  filtered_neighbors=t[0]
  dist_matrix=t[1]
  if(filtered_neighbors):
    for idx in filtered_neighbors:
      Shortest_path(arr,idx[0],idx[1],dist_matrix)
  else:
    #print(dist_matrix)
    return dist_matrix
  return dist_matrix




In [31]:
arr=np.array([[0,0,0,0,0,0,0,0],
              [1,1,0,0,1,1,1,0],
              [1,1,0,0,1,1,1,0],
              [1,1,0,0,1,1,1,0],
              [1,1,0,0,1,1,1,0],
              [1,1,0,0,1,1,1,0],
              [1,1,0,0,1,1,1,0],
              [1,1,0,0,1,1,1,0]])

values=np.full_like(arr,1000)
values[0][0]=0
matrix=Shortest_path(arr,0,0,values)
shortest=Shortest_path(arr,0,0,values)[(arr.shape[0]-1)][(arr.shape[0]-1)]
if(shortest!=1000):
  print("Shortest value is: ",shortest)
  print(chessboard(drawpath(matrix,matrix.shape[0]-1,matrix.shape[0]-1)))
else:
  print('-1')

Shortest value is:  14
[[2 2 2 2 2 2 2 2]
 [1 1 0 0 1 1 1 2]
 [1 1 0 0 1 1 1 2]
 [1 1 0 0 1 1 1 2]
 [1 1 0 0 1 1 1 2]
 [1 1 0 0 1 1 1 2]
 [1 1 0 0 1 1 1 2]
 [1 1 0 0 1 1 1 2]]


In [32]:
 arr1=np.array([[0,0,0,0,0,1,0,0],
                [1,1,0,0,1,1,1,0],
                [0,1,0,0,0,0,1,0],
                [0,1,0,0,1,0,0,0],
                [0,1,1,1,1,1,1,0],
                [0,1,1,1,1,1,1,0],
                [0,1,1,1,1,1,1,0],
                [0,1,1,1,1,1,1,0]
         ]) 
values=np.full_like(arr,1000)
values[0][0]=0
matrix=Shortest_path(arr1,0,0,values)
shortest=matrix[(arr1.shape[0]-1)][(arr1.shape[0]-1)]
if(shortest!=1000):
  print("Shortest value is: ",shortest)
  print(chessboard(drawpath(matrix,matrix.shape[0]-1,matrix.shape[0]-1)))
else:
  print('-1')

Shortest value is:  14
[[2 2 2 2 0 1 0 0]
 [1 1 0 2 1 1 1 0]
 [1 1 0 2 2 2 1 0]
 [1 1 0 0 1 2 2 2]
 [1 1 1 1 1 1 1 2]
 [1 1 1 1 1 1 1 2]
 [1 1 1 1 1 1 1 2]
 [1 1 1 1 1 1 1 2]]


In [33]:
arr2=np.array([[0,0,0,1,1,1,1,1],
               [1,1,0,0,1,1,1,1],
               [1,1,0,0,1,1,1,1],
               [1,1,0,0,1,1,1,1],
               [1,1,0,0,1,1,1,1],
               [1,1,0,0,0,0,1,1],
               [1,1,0,1,1,0,0,0],
               [1,1,0,0,1,0,0,0]
        ])
values=np.full_like(arr,1000)
values[0][0]=0
matrix=Shortest_path(arr2,0,0,values)
shortest=matrix[(arr2.shape[0]-1)][(arr2.shape[0]-1)]
if(shortest!=1000):
  print("Shortest value is: ",shortest)
  print(chessboard(drawpath(matrix,matrix.shape[0]-1,matrix.shape[0]-1)))
else:
  print('-1')

Shortest value is:  14
[[2 2 2 1 1 1 1 1]
 [1 1 2 2 1 1 1 1]
 [1 1 0 2 1 1 1 1]
 [1 1 0 2 1 1 1 1]
 [1 1 0 2 1 1 1 1]
 [1 1 0 2 2 2 1 1]
 [1 1 0 1 1 2 2 2]
 [1 1 0 0 1 0 0 2]]


In [34]:
 arr3=np.array([[0,0,0,0,0,0,0,0],
                [1,1,0,0,1,1,1,0],
               [0,1,0,0,1,1,1,0],
               [0,1,0,0,1,1,1,1],
               [0,1,1,1,1,1,1,0],
               [0,1,1,1,1,1,1,0],
               [0,1,1,1,1,1,1,0],
               [0,1,1,1,1,1,1,0]
         ])
values=np.full_like(arr,1000)
values[0][0]=0
matrix=Shortest_path(arr3,0,0,values)
shortest=matrix[(arr3.shape[0]-1)][(arr3.shape[0]-1)]
if(shortest!=1000):
  print("Shortest value is: ",shortest)
  print(chessboard(drawpath(matrix,matrix.shape[0]-1,matrix.shape[0]-1)))
else:
  print('-1')

-1
